# Generated by Django 3.2.9 on 2021-11-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
